config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do |variable|
    resources :doses, only: :create
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @doses = @cocktail.doses
      render "cocktails/show"
    end
  end

  def destroy
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<nav class="navbar navbar-light">
  <div class="d-flex justify-content-between align-item-center w-100">
    <%= image_tag "shake-it-off.jpg", alt: "alttext", height:"90" %>
    <%= link_to new_cocktail_path do  %>
      <button class="btn btn-outline my-2 my-sm-0" type="submit">Add a new cocktail</button>
    <% end %>
  </div>
</nav>

<div class="container">
  <div class = "row">
    <% @cocktails.each do |cocktail| %>
      <div class=" col-lg-4" style="width: 18rem;">
        <div class="card mb-3">
          <%= cl_image_tag cocktail.photo.key, height: 300, width: 400, crop: :fill, class: "card-img-top" %>
          <div class="card-body ">
            <h5 class="card-title"><%= cocktail.name.truncate(30) %></h5>
            <p class="card-text"><%#= cocktail.ingredients %></p>
            <a href="<%= cocktail_path(cocktail) %>" class="card-link">More info</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail:</h1>
<div class= "container">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file  %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name%></h1>
<div class="d-flex p-5 justify-content-around">
  <div class="container">
    <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
  </div>
  <div class="container">
    <h3>Cocktail formula:</h3>
    <% @doses.each do |dose| %>
      <p><%= dose.description %>
      <%= dose.ingredient.name %>
      <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fas fa-times"></i>
      <% end %>
      </p>
    <% end %>
  </div>
  <div class ="container">
    <h3>Add to the cocktail formula:</h3>
      <div class="container">
        <%= simple_form_for [ @cocktail, @dose ] do |f| %>
        <%= f.association :ingredient, as: :select %>
        <%= f.input :description %>
        <%= f.submit %>
        <% end %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>